{{-- resources/views/delivery/index.blade.php --}}
@extends('layouts.admin')
@section('title', 'Deliveries - Distributor Portal')
@section('page-content')
<div x-data="deliveryData()" x-init="init()" class="max-w-7xl mx-auto px-2 sm:px-4">
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4 gap-3"><div><h1 class="text-xl sm:text-2xl font-bold text-gray-800">Deliveries</h1><p class="text-sm text-gray-500 mt-0.5">Track order deliveries to shops</p></div></div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-2 mb-3"><div class="flex flex-col sm:flex-row items-stretch gap-2"><div class="relative max-w-xs w-full"><svg class="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg><input type="text" x-model="search" @input.debounce.300ms="doSearch()" placeholder="Search deliveries..." class="w-full pl-8 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"></div><select x-model="filterStatus" @change="doSearch()" class="border border-gray-200 rounded-lg px-2.5 py-1.5 text-xs focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"><option value="">All Statuses</option><option value="Pending">Pending</option><option value="Dispatched">Dispatched</option><option value="In Transit">In Transit</option><option value="Delivered">Delivered</option><option value="Failed">Failed</option></select><button @click="search='';filterStatus='';doSearch()" class="text-xs text-gray-500 hover:text-gray-700 px-2.5 py-1.5 rounded-lg hover:bg-gray-100 transition-colors whitespace-nowrap">Clear</button></div></div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"><div class="table-responsive"><table class="table-card-sm min-w-full divide-y divide-gray-200">
        <thead class="table-header-branded"><tr><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider">#</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">SO #</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">Shop</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden md:table-cell">Driver</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider">Date</th><th class="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider">Status</th></tr></thead>
        <tbody class="bg-white divide-y divide-gray-100">
            <template x-if="pager.loading"><tr><td colspan="6" class="px-6 py-20 text-center"><div class="flex flex-col items-center gap-3"><svg class="spinner w-10 h-10 text-primary" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg><div><p class="text-sm font-medium text-gray-400">Loading data...</p><p class="text-xs text-gray-400 mt-0.5">Please wait a moment</p></div></div></td></tr></template>
            <template x-if="!pager.loading && pager.items.length === 0"><tr><td colspan="6" class="px-6 py-20 text-center"><div class="max-w-sm mx-auto"><svg class="w-16 h-16 text-gray-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2" d="M8.25 18.75a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h6m-9 0H3.375a1.125 1.125 0 01-1.125-1.125V14.25m17.25 4.5a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h1.125c.621 0 1.129-.504 1.09-1.124a17.902 17.902 0 00-3.213-9.193 2.056 2.056 0 00-1.58-.86H14.25M16.5 18.75h-2.25m0-11.177v-.958c0-.568-.422-1.048-.987-1.106a48.554 48.554 0 00-10.026 0 1.106 1.106 0 00-.987 1.106v7.635m12-6.677v6.677m0 4.5v-4.5m0 0h-12"/></svg><h3 class="text-base font-semibold text-gray-400 mb-1">No Deliveries Yet</h3><p class="text-sm text-gray-400">Deliveries appear when sales orders are shipped</p></div></td></tr></template>
            <template x-for="(item, index) in pager.items" :key="item.id"><tr class="hover:bg-gray-50 transition-colors"><td class="px-3 py-3 text-sm text-gray-500 whitespace-nowrap" data-label="#" x-text="(pager.currentPage-1)*pager.perPage+index+1"></td><td class="px-3 py-3 text-sm font-mono text-primary hidden sm:table-cell" data-label="SO #" x-text="item.sales_order?.so_number||''"></td><td class="px-3 py-3 text-sm text-gray-600 whitespace-nowrap hidden sm:table-cell" data-label="Shop" x-text="item.shop?.name||''"></td><td class="px-3 py-3 text-sm text-gray-600 whitespace-nowrap hidden md:table-cell" data-label="Driver" x-text="item.driver_name||'-'"></td><td class="px-3 py-3 text-sm text-gray-600 whitespace-nowrap" data-label="Date" x-text="item.delivery_date||'Pending'"></td><td class="px-3 py-3 text-center whitespace-nowrap" data-label="Status"><span class="px-2 py-0.5 text-xs rounded-full font-medium" :class="{'bg-gray-200 text-gray-600':item.status==='Pending','bg-blue-100 text-blue-700':item.status==='Dispatched','bg-yellow-100 text-yellow-700':item.status==='In Transit','bg-green-100 text-green-700':item.status==='Delivered','bg-red-100 text-red-700':item.status==='Failed'}" x-text="item.status"></span></td></tr></template>
        </tbody>
    </table></div>@include('components.pagination-footer', ['prefix' => 'pager.'])</div>
</div>
@endsection
@push('scripts')<script>function deliveryData(){return{pager:{loading:true,items:[],currentPage:1,perPage:10,total:0,totalPages:1,get visiblePages(){return[]},fetchPage(){return Promise.resolve(false)},setSearch(){},refresh(){return Promise.resolve(false)},goToPage(){},changePerPage(){}},search:'',filterStatus:'',async init(){try{this.pager=$store.pager.create({endpoint:'/api/v1/delivery',perPage:10})}catch(e){console.error('Pager create failed:',e);this.pager.loading=false;return}this.pager.fetchPage()},doSearch(){try{var params={search:this.search||undefined};if(this.filterStatus)params.status=this.filterStatus;this.pager.setSearch(params)}catch(e){this.search=''}}}}</script>@endpush
