{{-- resources/views/sales-order/index.blade.php --}}
@extends('layouts.admin')
@section('title', 'Sales Orders - Distributor Portal')
@section('page-content')
<div x-data="soData()" x-init="init()" class="max-w-7xl mx-auto px-2 sm:px-4">
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4 gap-3">
        <div><h1 class="text-xl sm:text-2xl font-bold text-gray-800">Sales Orders</h1><p class="text-sm text-gray-500 mt-0.5">Orders from shops</p></div>
        <button @click="openCreate()" class="bg-primary hover:bg-primary-dark text-white px-4 py-2.5 rounded-xl font-medium text-sm shadow-md flex items-center gap-2 whitespace-nowrap"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>New Sales Order</button>
    </div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-2 mb-3">
        <div class="flex flex-col sm:flex-row items-stretch gap-2">
            <div class="relative max-w-xs w-full"><svg class="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg><input type="text" x-model="search" @input.debounce.300ms="doSearch()" placeholder="Search SO number..." class="w-full pl-8 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"></div>
            <select x-model="filterStatus" @change="doSearch()" class="border border-gray-200 rounded-lg px-2.5 py-1.5 text-xs focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"><option value="">All Statuses</option><option value="Draft">Draft</option><option value="Confirmed">Confirmed</option><option value="Processing">Processing</option><option value="Ready">Ready</option><option value="Delivered">Delivered</option><option value="Cancelled">Cancelled</option></select>
            <button @click="search=''; filterStatus=''; doSearch()" class="text-xs text-gray-500 hover:text-gray-700 px-2.5 py-1.5 rounded-lg hover:bg-gray-100 transition-colors whitespace-nowrap">Clear</button>
        </div>
    </div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"><div class="table-responsive"><table class="table-card-sm min-w-full divide-y divide-gray-200">
        <thead class="table-header-branded"><tr><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider">SO #</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider">Shop</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">Date</th><th class="px-3 py-3 text-right text-xs font-semibold uppercase tracking-wider">Total</th><th class="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider">Status</th><th class="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider w-36">Actions</th></tr></thead>
        <tbody class="bg-white divide-y divide-gray-100">
            <template x-if="pager.loading"><tr><td colspan="6" class="px-6 py-20 text-center"><div class="flex flex-col items-center gap-3"><svg class="spinner w-10 h-10 text-primary" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg><div><p class="text-sm font-medium text-gray-400">Loading data...</p><p class="text-xs text-gray-400 mt-0.5">Please wait a moment</p></div></div></td></tr></template>
            <template x-if="!pager.loading && pager.items.length === 0"><tr><td colspan="6" class="px-6 py-20 text-center"><div class="max-w-sm mx-auto"><svg class="w-16 h-16 text-gray-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/></svg><h3 class="text-base font-semibold text-gray-400 mb-1">No Sales Orders Found</h3><p class="text-sm text-gray-400">Click New Sales Order to create one</p></div></td></tr></template>
            <template x-for="(item, index) in pager.items" :key="item.id"><tr class="hover:bg-gray-50 transition-colors"><td class="px-3 py-3 text-sm font-mono font-medium text-primary whitespace-nowrap" data-label="SO #" x-text="item.so_number"></td><td class="px-3 py-3 text-sm font-medium text-gray-800 whitespace-nowrap" data-label="Shop" x-text="item.shop?.name || ''"></td><td class="px-3 py-3 text-sm text-gray-600 whitespace-nowrap hidden sm:table-cell" data-label="Date" x-text="item.order_date"></td><td class="px-3 py-3 text-sm font-semibold text-gray-700 text-right whitespace-nowrap" data-label="Total" x-text="'$'+parseFloat(item.grand_total||0).toFixed(2)"></td><td class="px-3 py-3 text-center whitespace-nowrap" data-label="Status"><span class="px-2 py-0.5 text-xs rounded-full font-medium" :class="{'bg-gray-200 text-gray-600':item.status==='Draft','bg-blue-100 text-blue-700':item.status==='Confirmed','bg-yellow-100 text-yellow-700':item.status==='Processing','bg-purple-100 text-purple-700':item.status==='Ready','bg-green-100 text-green-700':item.status==='Delivered','bg-red-100 text-red-700':item.status==='Cancelled'}" x-text="item.status"></span></td><td class="px-3 py-3 text-center whitespace-nowrap" data-label="Actions"><div class="flex justify-center gap-1"><select @change="updateStatus(item, $event.target.value)" class="border border-gray-200 rounded px-1.5 py-1 text-xs focus:ring-1 focus:ring-primary/30 outline-none"><option value="">Change Status</option><option value="Confirmed">Confirm</option><option value="Processing">Processing</option><option value="Ready">Ready</option><option value="Delivered">Delivered</option><option value="Cancelled">Cancel</option></select></div></td></tr></template>
        </tbody>
    </table></div>@include('components.pagination-footer', ['prefix' => 'pager.'])</div>
</div>
@endsection
@push('scripts')<script>function soData(){return{pager:{loading:true,items:[],currentPage:1,perPage:10,total:0,totalPages:1,get visiblePages(){return[]},fetchPage(){return Promise.resolve(false)},setSearch(){},refresh(){return Promise.resolve(false)},goToPage(){},changePerPage(){}},search:'',filterStatus:'',async init(){try{this.pager=$store.pager.create({endpoint:'/api/v1/sales-order',perPage:10})}catch(e){console.error('Pager create failed:',e);this.pager.loading=false;return}this.pager.fetchPage()},doSearch(){try{var params={search:this.search||undefined};if(this.filterStatus)params.status=this.filterStatus;this.pager.setSearch(params)}catch(e){this.search=''}},openCreate(){window.location.href='/company_admin/sales_orders/create'},async updateStatus(item, status){if(!status)return;try{await $store.api.put('/api/v1/sales-order/'+item.id+'/status',{status:status});$store.toast.success('Status updated to '+status);this.pager.refresh()}catch(e){$store.toast.error(e.message||'Failed to update status')}}}}</script>@endpush
