{{-- resources/views/payment/index.blade.php --}}
@extends('layouts.admin')
@section('title', 'Payments - Distributor Portal')
@section('page-content')
<div x-data="paymentData()" x-init="init()" class="max-w-7xl mx-auto px-2 sm:px-4">
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4 gap-3"><div><h1 class="text-xl sm:text-2xl font-bold text-gray-800">Payments</h1><p class="text-sm text-gray-500 mt-0.5">Payment collection history</p></div></div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-2 mb-3"><div class="flex flex-col sm:flex-row items-stretch gap-2"><div class="relative max-w-xs w-full"><svg class="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg><input type="text" x-model="search" @input.debounce.300ms="doSearch()" placeholder="Search payments..." class="w-full pl-8 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"></div><select x-model="filterMethod" @change="doSearch()" class="border border-gray-200 rounded-lg px-2.5 py-1.5 text-xs focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"><option value="">All Methods</option><option value="Cash">Cash</option><option value="Bank Transfer">Bank Transfer</option><option value="Cheque">Cheque</option><option value="Mobile Money">Mobile Money</option><option value="Credit Card">Credit Card</option></select><button @click="search='';filterMethod='';doSearch()" class="text-xs text-gray-500 hover:text-gray-700 px-2.5 py-1.5 rounded-lg hover:bg-gray-100 transition-colors whitespace-nowrap">Clear</button></div></div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"><div class="table-responsive"><table class="table-card-sm min-w-full divide-y divide-gray-200">
        <thead class="table-header-branded"><tr><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider">#</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">Invoice</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">Shop</th><th class="px-3 py-3 text-right text-xs font-semibold uppercase tracking-wider">Amount</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden md:table-cell">Method</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden md:table-cell">Date</th></tr></thead>
        <tbody class="bg-white divide-y divide-gray-100">
            <template x-if="pager.loading"><tr><td colspan="6" class="px-6 py-20 text-center"><div class="flex flex-col items-center gap-3"><svg class="spinner w-10 h-10 text-primary" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg><div><p class="text-sm font-medium text-gray-400">Loading data...</p><p class="text-xs text-gray-400 mt-0.5">Please wait a moment</p></div></div></td></tr></template>
            <template x-if="!pager.loading && pager.items.length === 0"><tr><td colspan="6" class="px-6 py-20 text-center"><div class="max-w-sm mx-auto"><svg class="w-16 h-16 text-gray-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><h3 class="text-base font-semibold text-gray-400 mb-1">No Payments Yet</h3><p class="text-sm text-gray-400">Payments appear when recorded against invoices</p></div></td></tr></template>
            <template x-for="(item, index) in pager.items" :key="item.id"><tr class="hover:bg-gray-50 transition-colors"><td class="px-3 py-3 text-sm text-gray-500 whitespace-nowrap" data-label="#" x-text="(pager.currentPage-1)*pager.perPage+index+1"></td><td class="px-3 py-3 text-sm font-mono text-primary hidden sm:table-cell" data-label="Invoice" x-text="item.invoice?.invoice_number||''"></td><td class="px-3 py-3 text-sm text-gray-600 whitespace-nowrap hidden sm:table-cell" data-label="Shop" x-text="item.shop?.name||''"></td><td class="px-3 py-3 text-sm font-semibold text-green-600 text-right whitespace-nowrap" data-label="Amount" x-text="'$'+parseFloat(item.amount||0).toFixed(2)"></td><td class="px-3 py-3 text-sm text-gray-600 whitespace-nowrap hidden md:table-cell" data-label="Method" x-text="item.payment_method||'Cash'"></td><td class="px-3 py-3 text-sm text-gray-600 whitespace-nowrap hidden md:table-cell" data-label="Date" x-text="item.payment_date"></td></tr></template>
        </tbody>
    </table></div>@include('components.pagination-footer', ['prefix' => 'pager.'])</div>
</div>
@endsection
@push('scripts')<script>function paymentData(){return{pager:{loading:true,items:[],currentPage:1,perPage:10,total:0,totalPages:1,get visiblePages(){return[]},fetchPage(){return Promise.resolve(false)},setSearch(){},refresh(){return Promise.resolve(false)},goToPage(){},changePerPage(){}},search:'',filterMethod:'',async init(){try{this.pager=Alpine.store('pager').create({endpoint:'/api/v1/payment',perPage:10})}catch(e){console.error('Pager create failed:',e);this.pager.loading=false;return}this.pager.fetchPage()},doSearch(){try{var params={search:this.search||undefined};if(this.filterMethod)params.payment_method=this.filterMethod;this.pager.setSearch(params)}catch(e){this.search=''}}}}</script>@endpush
