{{-- resources/views/stock/index.blade.php --}}
@extends('layouts.admin')
@section('title', 'Stock Overview - Distributor Portal')
@section('page-content')
<div x-data="stockData()" x-init="init()" class="max-w-7xl mx-auto px-2 sm:px-4">
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4 gap-3">
        <div><h1 class="text-xl sm:text-2xl font-bold text-gray-800">Stock Overview</h1><p class="text-sm text-gray-500 mt-0.5">Inventory levels across all warehouses</p></div>
    </div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-2 mb-3">
        <div class="flex flex-col sm:flex-row items-stretch gap-2">
            <div class="relative max-w-xs w-full"><svg class="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg><input type="text" x-model="search" @input.debounce.300ms="doSearch()" placeholder="Search products..." class="w-full pl-8 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"></div>
            <select x-model="filterWarehouse" @change="doSearch()" class="border border-gray-200 rounded-lg px-2.5 py-1.5 text-xs focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"><option value="">All Warehouses</option><template x-for="w in warehouses" :key="w.id"><option :value="w.id" x-text="w.name"></option></template></select>
            <button @click="search=''; filterWarehouse=''; doSearch()" class="text-xs text-gray-500 hover:text-gray-700 px-2.5 py-1.5 rounded-lg hover:bg-gray-100 transition-colors whitespace-nowrap">Clear</button>
        </div>
    </div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"><div class="table-responsive"><table class="table-card-sm min-w-full divide-y divide-gray-200">
        <thead class="table-header-branded"><tr><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider">#</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider">Product</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">Warehouse</th><th class="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider">Total</th><th class="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">Reserved</th><th class="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider">Available</th><th class="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">Status</th></tr></thead>
        <tbody class="bg-white divide-y divide-gray-100">
            <template x-if="pager.loading"><tr><td colspan="7" class="px-6 py-20 text-center"><div class="flex flex-col items-center gap-3"><svg class="spinner w-10 h-10 text-primary" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg><div><p class="text-sm font-medium text-gray-400">Loading data...</p><p class="text-xs text-gray-400 mt-0.5">Please wait a moment</p></div></div></td></tr></template>
            <template x-if="!pager.loading && pager.items.length === 0"><tr><td colspan="7" class="px-6 py-20 text-center"><div class="max-w-sm mx-auto"><svg class="w-16 h-16 text-gray-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/></svg><h3 class="text-base font-semibold text-gray-400 mb-1">No Stock Records Yet</h3><p class="text-sm text-gray-400">Add products and receive purchase orders to see stock</p></div></td></tr></template>
            <template x-for="(item, index) in pager.items" :key="item.id"><tr class="hover:bg-gray-50 transition-colors"><td class="px-3 py-3 text-sm text-gray-500 whitespace-nowrap" data-label="#" x-text="(pager.currentPage-1)*pager.perPage+index+1"></td><td class="px-3 py-3 text-sm font-medium text-gray-800 whitespace-nowrap" data-label="Product" x-text="item.product?.material_name || ''"></td><td class="px-3 py-3 text-sm text-gray-600 whitespace-nowrap hidden sm:table-cell" data-label="Warehouse" x-text="item.warehouse?.name || ''"></td><td class="px-3 py-3 text-center text-sm font-semibold text-gray-700 whitespace-nowrap" data-label="Total" x-text="item.total_quantity"></td><td class="px-3 py-3 text-center text-sm text-gray-600 whitespace-nowrap hidden sm:table-cell" data-label="Reserved" x-text="item.reserved_quantity"></td><td class="px-3 py-3 text-center whitespace-nowrap" data-label="Available"><span class="px-2 py-0.5 text-xs rounded-full font-semibold" :class="{'bg-green-100 text-green-700': item.available_quantity > item.reorder_level, 'bg-yellow-100 text-yellow-700': item.available_quantity > 0 && item.available_quantity <= item.reorder_level, 'bg-red-100 text-red-700': item.available_quantity <= 0}" x-text="item.available_quantity"></span></td><td class="px-3 py-3 text-center whitespace-nowrap hidden sm:table-cell" data-label="Status"><span class="px-2 py-0.5 text-xs rounded-full font-medium" :class="{'bg-green-100 text-green-700': item.available_quantity > item.reorder_level, 'bg-yellow-100 text-yellow-700': item.available_quantity > 0 && item.available_quantity <= item.reorder_level, 'bg-red-100 text-red-700': item.available_quantity <= 0}" x-text="item.available_quantity > item.reorder_level ? 'In Stock' : (item.available_quantity > 0 ? 'Low Stock' : 'Out of Stock')"></span></td></tr></template>
        </tbody>
    </table></div>@include('components.pagination-footer', ['prefix' => 'pager.'])</div>
</div>
@endsection
@push('scripts')<script>function stockData(){return{pager:{loading:true,items:[],currentPage:1,perPage:10,total:0,totalPages:1,get visiblePages(){return[]},fetchPage(){return Promise.resolve(false)},setSearch(){},refresh(){return Promise.resolve(false)},goToPage(){},changePerPage(){}},warehouses:[],search:'',filterWarehouse:'',async init(){try{this.pager=Alpine.store('pager').create({endpoint:'/api/v1/stock/overview',perPage:10})}catch(e){console.error('Pager create failed:',e);this.pager.loading=false;return}this.fetchDependencies();this.pager.fetchPage()},doSearch(){try{var params={search:this.search||undefined};if(this.filterWarehouse)params.warehouse_id=this.filterWarehouse;this.pager.setSearch(params)}catch(e){this.search=''}},async fetchDependencies(){try{var d=await Alpine.store('api').get('/api/v1/warehouse',{per_page:200});if(d&&d.status)this.warehouses=Array.isArray(d.data)?d.data:(d.data?.data||[])}catch(e){}}}}</script>@endpush
