{{-- resources/views/purchase-return/index.blade.php --}}
@extends('layouts.admin')
@section('title', 'Purchase Returns - Distributor Portal')
@section('page-content')
<div x-data="prData()" x-init="init()" class="max-w-7xl mx-auto px-2 sm:px-4">
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4 gap-3">
        <div><h1 class="text-xl sm:text-2xl font-bold text-gray-800">Purchase Returns</h1><p class="text-sm text-gray-500 mt-0.5">Returns to suppliers</p></div>
        <button @click="openAddModal()" class="bg-primary hover:bg-primary-dark text-white px-4 py-2.5 rounded-xl font-medium text-sm shadow-md flex items-center gap-2 whitespace-nowrap"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>New Return</button>
    </div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-2 mb-3">
        <div class="flex flex-col sm:flex-row items-stretch gap-2"><div class="relative max-w-xs w-full"><svg class="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg><input type="text" x-model="search" @input.debounce.300ms="doSearch()" placeholder="Search returns..." class="w-full pl-8 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"></div><select x-model="filterStatus" @change="doSearch()" class="border border-gray-200 rounded-lg px-2.5 py-1.5 text-xs focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"><option value="">All Statuses</option><option value="Pending">Pending</option><option value="Approved">Approved</option><option value="Completed">Completed</option><option value="Rejected">Rejected</option></select><button @click="search='';filterStatus='';doSearch()" class="text-xs text-gray-500 hover:text-gray-700 px-2.5 py-1.5 rounded-lg hover:bg-gray-100 transition-colors whitespace-nowrap">Clear</button></div>
    </div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"><div class="table-responsive"><table class="table-card-sm min-w-full divide-y divide-gray-200">
        <thead class="table-header-branded"><tr><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider">Return #</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">Supplier</th><th class="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wider hidden sm:table-cell">Date</th><th class="px-3 py-3 text-right text-xs font-semibold uppercase tracking-wider">Total</th><th class="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider">Status</th><th class="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wider hidden md:table-cell">Items</th></tr></thead>
        <tbody class="bg-white divide-y divide-gray-100">
            <template x-if="pager.loading"><tr><td colspan="6" class="px-6 py-20 text-center"><div class="flex flex-col items-center gap-3"><svg class="spinner w-10 h-10 text-primary" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg><div><p class="text-sm font-medium text-gray-400">Loading data...</p><p class="text-xs text-gray-400 mt-0.5">Please wait a moment</p></div></div></td></tr></template>
            <template x-if="!pager.loading && pager.items.length === 0"><tr><td colspan="6" class="px-6 py-20 text-center"><div class="max-w-sm mx-auto"><svg class="w-16 h-16 text-gray-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2" d="M16 14l-4-4-4 4"/></svg><h3 class="text-base font-semibold text-gray-400 mb-1">No Returns Yet</h3><p class="text-sm text-gray-400">Purchase returns appear here when created</p></div></td></tr></template>
            <template x-for="(item, index) in pager.items" :key="item.id"><tr class="hover:bg-gray-50"><td class="px-3 py-3 text-sm font-mono text-primary" x-text="item.return_number"></td><td class="px-3 py-3 text-sm text-gray-600 hidden sm:table-cell" x-text="item.supplier?.name||''"></td><td class="px-3 py-3 text-sm text-gray-600 hidden sm:table-cell" x-text="item.return_date"></td><td class="px-3 py-3 text-sm font-semibold text-red-600 text-right" x-text="'$'+(+item.total_amount||0).toFixed(2)"></td><td class="px-3 py-3 text-center"><span class="px-2 py-0.5 text-xs rounded-full font-medium" :class="{'bg-yellow-100 text-yellow-700':item.status==='Pending','bg-blue-100 text-blue-700':item.status==='Approved','bg-green-100 text-green-700':item.status==='Completed','bg-red-100 text-red-700':item.status==='Rejected'}" x-text="item.status"></span></td><td class="px-3 py-3 text-sm text-gray-500 hidden md:table-cell" x-text="item.items?.length||0"></td></tr></template>
        </tbody>
    </table></div>@include('components.pagination-footer', ['prefix' => 'pager.'])</div>

    {{-- Add Modal --}}
    <div x-show="modalOpen" x-cloak class="fixed inset-0 z-50 flex items-center justify-center p-4" x-transition.opacity @keydown.escape.window="closeModal()"><div class="fixed inset-0 bg-black/50 backdrop-blur-sm" @click="closeModal()"></div><div class="relative bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto z-10" @click.outside="closeModal()"><div class="flex items-center justify-between px-6 py-4 border-b sticky top-0 bg-white rounded-t-2xl z-10"><h3 class="text-lg font-semibold text-gray-800">New Purchase Return</h3><button @click="closeModal()" class="p-1 rounded-lg text-gray-400 hover:text-gray-600 hover:bg-gray-100"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></div><form @submit.prevent="saveReturn()" class="p-6 space-y-4"><div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-1.5">Supplier <span class="text-red-500">*</span></label><select x-model="form.supplier_id" class="w-full border border-gray-300 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"><option value="">Select supplier</option><template x-for="s in suppliers" :key="s.id"><option :value="s.id" x-text="s.name"></option></template></select><p x-show="errors.supplier_id" class="text-red-500 text-xs mt-1" x-text="errors.supplier_id"></p></div><div><label class="block text-sm font-medium text-gray-700 mb-1.5">Return Date</label><input type="date" x-model="form.return_date" class="w-full border border-gray-300 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"></div></div><div><label class="block text-sm font-medium text-gray-700 mb-1.5">Reason</label><textarea x-model="form.reason" rows="2" class="w-full border border-gray-300 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none"></textarea></div>
        <div class="border-t pt-4"><h4 class="text-sm font-semibold text-gray-700 mb-3">Return Items</h4><div class="grid grid-cols-12 gap-2 items-end mb-2"><div class="col-span-5"><select x-model="newItem.product_id" class="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"><option value="">Select product</option><template x-for="p in products" :key="p.id"><option :value="p.id" x-text="p.material_name"></option></template></select></div><div class="col-span-2"><input type="number" min="1" x-model="newItem.quantity" placeholder="Qty" class="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"></div><div class="col-span-2"><input type="number" min="0" step="0.01" x-model="newItem.unit_price" placeholder="Price" class="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"></div><div class="col-span-2"><input type="text" x-model="newItem.reason" placeholder="Reason" class="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"></div><div class="col-span-1"><button type="button" @click="addItem()" :disabled="!newItem.product_id||!newItem.quantity" class="w-full bg-primary hover:bg-primary-dark text-white py-2 rounded-lg text-sm font-medium disabled:opacity-50">+</button></div></div>
            <template x-if="form.items.length"><div class="mt-3"><template x-for="(it, i) in form.items" :key="i"><div class="flex items-center gap-2 py-1 text-sm"><span class="flex-1" x-text="it.product_name"></span><span class="w-16 text-center" x-text="'x'+it.quantity"></span><span class="w-20 text-right text-gray-600" x-text="'$'+(it.quantity*it.unit_price).toFixed(2)"></span><button type="button" @click="form.items.splice(i,1)" class="text-red-400 hover:text-red-600 p-1"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></div></template></div></template></div>
        <div class="flex justify-end gap-3 pt-2"><button type="button" @click="closeModal()" class="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-xl">Cancel</button><button type="submit" :disabled="saving" class="px-5 py-2 text-sm font-medium text-white bg-primary hover:bg-primary-dark rounded-xl disabled:opacity-50 flex items-center gap-2"><svg x-show="saving" class="spinner w-4 h-4 text-white" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg><span x-text="saving?'Saving...':'Submit Return'"></span></button></div></form></div></div>
</div>
@endsection
@push('scripts')<script>function prData(){return{pager:{loading:true,items:[],currentPage:1,perPage:10,total:0,totalPages:1,get visiblePages(){return[]},fetchPage(){return Promise.resolve(false)},setSearch(){},refresh(){return Promise.resolve(false)},goToPage(){},changePerPage(){}},suppliers:[],products:[],search:'',filterStatus:'',modalOpen:false,saving:false,form:{supplier_id:'',return_date:new Date().toISOString().split('T')[0],reason:'',items:[]},newItem:{product_id:'',quantity:1,unit_price:0,reason:''},errors:{},async init(){try{this.pager=Alpine.store('pager').create({endpoint:'/api/v1/purchase-return',perPage:10})}catch(e){this.pager.loading=false;return}this.fetchDeps();this.pager.fetchPage()},doSearch(){var p={search:this.search||undefined};if(this.filterStatus)p.status=this.filterStatus;this.pager.setSearch(p)},async fetchDeps(){try{var d=await Alpine.store('api').get('/api/v1/supplier',{per_page:500});if(d&&d.status)this.suppliers=Array.isArray(d.data)?d.data:(d.data?.data||[]);var m=await Alpine.store('api').get('/api/v1/material',{per_page:500});if(m&&m.status)this.products=Array.isArray(m.data)?m.data:(m.data?.data||[])}catch(e){}},openAddModal(){this.form={supplier_id:'',return_date:new Date().toISOString().split('T')[0],reason:'',items:[]};this.errors={};this.modalOpen=true},closeModal(){this.modalOpen=false},addItem(){if(!this.newItem.product_id||!this.newItem.quantity)return;var p=this.products.find(function(p){return p.id==this.newItem.product_id},this);this.form.items.push({product_id:this.newItem.product_id,product_name:p?p.material_name:'Product',quantity:parseInt(this.newItem.quantity),unit_price:parseFloat(this.newItem.unit_price)||parseFloat(p?p.price:0),reason:this.newItem.reason});this.newItem={product_id:'',quantity:1,unit_price:0,reason:''}},async saveReturn(){if(!this.form.supplier_id){this.errors.supplier_id='Select a supplier';return}if(!this.form.items.length){Alpine.store('toast').error('Add at least one item');return}this.saving=true;try{var d=await Alpine.store('api').post('/api/v1/purchase-return',{...this.form,items:this.form.items.map(function(i){return{product_id:i.product_id,quantity:i.quantity,unit_price:i.unit_price,reason:i.reason}})});if(d.status){Alpine.store('toast').success('Return created');this.closeModal();this.pager.refresh()}}catch(e){Alpine.store('toast').error(e.message||'Failed')}finally{this.saving=false}}}}</script>@endpush
